version: '3.4'
services:
  mongo:
    image: mongo
    command: mongod --port 27017
    ports:
      - "27017:27017"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
  app:
    build: 
      context: ./InciDashboard_i3b
    ports: 
      - "8090:8090"
    links:
      - kafka
      - zookeeper
      - mongo